import { CommentTemplate } from "@/lib/types/dashboard";

export const mockCommentTemplates: CommentTemplate[] = [
    {
        id: "ct_001",
        name: "Engagement Booster",
        content: "This is amazing! How did you come up with this? I need to try this!",
        platform: "instagram",
        tone: "friendly",
        isActive: true,
        stats: {
            timesUsed: 2340,
            avgEngagement: 4.2,
            lastUsed: "2024-02-03T14:30:00",
        },
        createdAt: "2024-01-15",
    },
    {
        id: "ct_002",
        name: "Question Hook",
        content: "Wait, is this real? How do I get started with this?",
        platform: "tiktok",
        tone: "casual",
        isActive: true,
        stats: {
            timesUsed: 1890,
            avgEngagement: 3.8,
            lastUsed: "2024-02-03T12:15:00",
        },
        createdAt: "2024-01-18",
    },
    {
        id: "ct_003",
        name: "FOMO Trigger",
        content: "Everyone's talking about this! Don't miss out on this opportunity",
        platform: "twitter",
        tone: "fomo",
        isActive: true,
        stats: {
            timesUsed: 1567,
            avgEngagement: 5.1,
            lastUsed: "2024-02-03T10:45:00",
        },
        createdAt: "2024-01-20",
    },
    {
        id: "ct_004",
        name: "Social Proof",
        content: "Just tried this and WOW! Thousands of people can't be wrong about this",
        platform: "facebook",
        tone: "friendly",
        isActive: true,
        stats: {
            timesUsed: 980,
            avgEngagement: 3.2,
            lastUsed: "2024-02-02T18:30:00",
        },
        createdAt: "2024-01-22",
    },
    {
        id: "ct_005",
        name: "Urgency Push",
        content: "This won't last long! Grab it while you can",
        platform: "instagram",
        tone: "urgent",
        isActive: false,
        stats: {
            timesUsed: 456,
            avgEngagement: 4.8,
            lastUsed: "2024-01-28T09:00:00",
        },
        createdAt: "2024-01-25",
    },
    {
        id: "ct_006",
        name: "Professional Inquiry",
        content: "Interesting approach. Could you share more about the methodology behind this?",
        platform: "linkedin",
        tone: "professional",
        isActive: true,
        stats: {
            timesUsed: 234,
            avgEngagement: 2.9,
            lastUsed: "2024-02-03T08:00:00",
        },
        createdAt: "2024-01-28",
    },
    {
        id: "ct_007",
        name: "Appreciation Post",
        content: "This is exactly what I needed today. Thank you for sharing!",
        platform: "instagram",
        tone: "friendly",
        isActive: true,
        stats: {
            timesUsed: 1245,
            avgEngagement: 3.5,
            lastUsed: "2024-02-03T16:20:00",
        },
        createdAt: "2024-01-30",
    },
    {
        id: "ct_008",
        name: "Scarcity Alert",
        content: "Only a few spots left! I almost missed this myself",
        platform: "tiktok",
        tone: "fomo",
        isActive: true,
        stats: {
            timesUsed: 789,
            avgEngagement: 5.4,
            lastUsed: "2024-02-03T11:30:00",
        },
        createdAt: "2024-02-01",
    },
];
