import Link from "next/link";
import { pageMetadata } from "@/lib/site";

export const metadata = pageMetadata("Privacy & Storage", "What stays in the local Attention Lab workspace, what an explicit save or export does, and how the server-side checker and optional provider differ.", "/privacy");

export default function PrivacyPage() {
  return (
    <main className="attention-page"><div className="attention-container">
      <header className="attention-page-header"><p className="attention-kicker">The data boundary</p><h1 className="attention-title">Your work.<br /><em>Your decision to save.</em></h1><p className="attention-lead">The local Lab, the opt-in Attention API and the server-side checker have different data boundaries. Here is what each one does with your input.</p></header>
      <div className="attention-reading-layout">
        <aside className="attention-reading-aside"><nav aria-label="Privacy contents"><p className="attention-kicker">On this page</p><a href="#workspace">Lab & trend notes</a><a href="#saving">Save, load & delete</a><a href="#exports">Downloads & clipboard</a><a href="#checker">The checker</a><a href="#attention-api">The shared Attention API</a><a href="#external">External services</a><a href="#limits">What is not verified</a></nav></aside>
        <div className="attention-reading-body">
          <section className="attention-reading-section" id="workspace"><p className="attention-kicker">01 / Browser workspace</p><h2>In memory by default.</h2><p>The Lab brief, manual trend notes, edited output and outcome entries stay in the browser’s active workspace. The new Lab and Trends tools do not send this content to our API, a model provider, a trend service or a publishing platform.</p><p>Use the site’s navigation to keep the same active brief across pages. Reloading or closing the page clears unsaved work. There is no automatic draft save, account, cloud sync or automatic publishing.</p><p>Atlas and platform links may carry stable catalogue IDs to preselect a mechanism or surface. They do not carry your pasted checker text or your brief content.</p></section>
          <section className="attention-reading-section" id="saving"><p className="attention-kicker">02 / An explicit local copy</p><h2>Save is a choice.</h2><p><strong>Save on this device</strong> writes one versioned draft to namespaced browser-local storage for this site. Saving again replaces that local draft. <strong>Load</strong> brings the saved draft back into the workspace; it is not loaded automatically on a visit.</p><p><strong>Delete</strong> removes the saved browser draft, not copies you downloaded or pasted elsewhere. Local storage is not a backup: clearing site data, browser policies, private browsing or a full storage quota can make it unavailable.</p><p>Drafts have a size limit and are validated when loaded or imported. A corrupt, incompatible or oversized draft is not silently treated as valid. Validation does not make a shared device private: other people with access to the same browser profile may be able to read its storage.</p><div className="attention-note">The existing site theme system may separately use browser storage for a theme preference. That preference is not the Lab draft. Use browser site-data controls if you want to remove all data for this site.</div></section>
          <section className="attention-reading-section" id="exports"><p className="attention-kicker">03 / Copies you control</p><h2>A download leaves the workspace.</h2><p>Exporting JSON creates a local file containing the workspace data you chose to export. Importing reads a selected file in your browser, validates its version and structure, and does not upload it. Import can replace the current workspace; keep an export if you need to preserve another brief.</p><p>Copying Markdown sends the text to your device’s clipboard when you request it. Clipboard managers, cloud clipboard settings, downloads folders and any app or person you share an export with are outside this app’s control.</p><p>Do not put passwords, payment details or private customer records into a brief. Deleting a browser draft does not erase downloaded files, clipboard history or shared copies.</p></section>
          <section className="attention-reading-section" id="checker"><p className="attention-kicker">04 / Server-side analysis</p><h2>The checker sends your submission.</h2><p>When you run the checker, the submitted text goes to this app’s own API for analysis. The checker can use a configured external model provider when available; its rule-based path remains available without a provider. This is not the Lab’s local-only processing path.</p><p>The application’s checker path does not persist submitted content as saved app records. That is narrower than saying no system ever retains anything: hosting infrastructure, logs and any configured provider may have their own processing or retention behavior, which has not been verified here.</p><p>Checker submissions are not added to Lab drafts, navigation URLs or automatic browser storage. Mechanism links carry only stable catalogue IDs. Avoid submitting secrets or other people’s sensitive personal information.</p><Link href="/check" className="attention-text-link">Go to the free checker <span aria-hidden="true">↗</span></Link></section>
          <section className="attention-reading-section" id="attention-api"><p className="attention-kicker">05 / An explicit remote call</p><h2>A shared engine, a separate data choice.</h2><p>Projects can explicitly call the versioned Attention API to read the catalogue, generate a brief or compare supplied counts. API and agenttool SDK calls send the selected request fields to FOMOengine, or to the separate origin the caller configures. This does not turn the browser Lab or Trends notebook into a remote workspace.</p><p>The Attention API uses deterministic templates and arithmetic. It does not call a model, connect to a database, fetch cited URLs, publish content or persist submitted content as application records. Request bodies are not written to application logs; hosting access metadata and infrastructure retention are separate and have not been independently verified.</p><p>The agenttool integration uses a separate credential-free client, not the authenticated AgentTool transport. It does not forward AgentTool tokens or cookies, collect repository contents, or upload drafts automatically. Never include secrets, private customer records or other people’s sensitive personal information. A source snapshot or catalogue digest is not a signature or proof that a caller’s claims are true.</p></section>
          <section className="attention-reading-section" id="external"><p className="attention-kicker">06 / Leaving this notebook</p><h2>Links are not data connectors.</h2><p>Research references and the Google Trends explorer open an external website only when you follow the link. The Trends notebook does not fetch that site’s contents. External sites apply their own privacy and storage policies.</p><p>Normal page and asset requests still reach the website’s hosting infrastructure. “Local workspace” describes how brief and note content is processed, not an offline website or a promise of anonymous browsing.</p><p>The optional <Link href="/audit">audit request</Link> prepares a metadata-only draft locally in your browser. You can copy it or explicitly open your email app and choose whether to send it. The form does not submit details to an intake server or save them under the Lab’s draft controls; any email you send is then handled by your email service and the recipient.</p></section>
          <section className="attention-reading-section" id="limits"><p className="attention-kicker">07 / Limits of this statement</p><h2>No blanket retention promise.</h2><p>This page describes the application behavior of these tools. Hosting logs, infrastructure retention, configured provider policies and device-level backups have not been independently verified. We do not turn “no application content persistence” into a universal “nothing saved” claim.</p><p>If you need a stricter boundary, use non-sensitive examples, avoid the server-side checker and remote Attention API calls, and do not explicitly save, copy or export a local draft.</p><Link href="/methodology" className="attention-text-link">Research and interpretation boundaries <span aria-hidden="true">↗</span></Link></section>
        </div>
      </div>
    </div></main>
  );
}
