import type { Platform, PlatformId } from "./schema";

export const PLATFORMS: readonly Platform[] = [
  {
    id: "instagram-feed",
    name: "Instagram Feed",
    channel: "social",
    surface: "Feed",
    kind: "ranked-surface",
    summary: "A personalized feed, not a single engagement leaderboard. Read this entry as a historical map of disclosed stages, not today's secret formula.",
    rankingDisclosure: "Historical Meta system card (2022). Feed candidates, predictions and ranking are described at a high level; current weights and behavior have not been verified. This is not Reels or Explore guidance.",
    signals: [
      {
        id: "instagram-feed-historical-stages",
        text: "Meta's historical Feed card describes gathering eligible content, using signals to predict likely interactions, and ranking candidates for a particular viewer.",
        kind: "official-disclosure",
        sourceIds: ["meta-feed-2022"],
        context: "Instagram Feed in the historical 2022 disclosure.",
        limitations: ["Not a current 2026 specification or a complete candidate-selection policy.", "Do not apply this Feed description to Reels or Explore."],
      },
      {
        id: "instagram-feed-historical-signals",
        text: "The historical disclosure describes information about content and a viewer's past activity and relationships as inputs to predictions, rather than a universal score visible to creators.",
        kind: "official-disclosure",
        sourceIds: ["meta-feed-2022"],
        context: "High-level signal families in the historical Feed system card.",
        limitations: ["No exact signal weights or causal return from obtaining a like, save or comment are established here.", "Creator-visible engagement is not a measurement of the internal ranking model."],
      },
    ],
    practicalChoices: [
      "Make the first image and caption identify who the post is useful for and what it delivers.",
      "Keep the visual, caption and landing promise consistent; use readable text and meaningful image descriptions.",
      "Choose one useful action such as saving an actual reference, not an engagement-bait demand to comment.",
    ],
    metric: {
      name: "Save rate (unique-account basis)",
      numerator: "Reached accounts that saved this post, counted once in the observation window",
      denominator: "Accounts reached by the same post in the same window",
      caveat: "Use this only if the same unique-account unit is available for both counts. Aggregate repeat events are not unique savers; unavailable counts stay blank rather than being inferred. Reach is not randomized exposure.",
    },
    qualityGuardrails: ["The saved post contains the promised reference or useful information.", "Review hides, unfollows and feedback about misleading expectations when available.", "Do not reward an engagement rate that comes with inaccessible text or a bait-and-switch."],
    confounders: ["Follower and non-follower mix", "Relationship history and personalized exposure", "Posting time, competing content and paid distribution", "Format changes or unequal reach between posts"],
    sourceIds: ["meta-feed-2022"],
  },
  {
    id: "tiktok-for-you",
    name: "TikTok For You",
    channel: "social",
    surface: "For You",
    kind: "ranked-surface",
    summary: "A recommendation surface distinct from Search. The available reference supports only a conservative, high-level account of its signals.",
    rankingDisclosure: "Official index only: the linked article body was access-restricted during the approved research. Current exact wording, weights and a complete For You pipeline were not verified.",
    signals: [
      {
        id: "tiktok-for-you-index-families",
        text: "TikTok's official help-index information groups recommendation inputs into user interactions, content information and user information.",
        kind: "official-disclosure",
        sourceIds: ["tiktok-recommendations"],
        context: "Official index-level information; direct article-body access was restricted.",
        limitations: ["Index only, not a freshly verified reading of the full For You documentation.", "No exact weights, watch-time threshold or guaranteed distribution sequence is known from this record.", "A broad signal family does not establish which creative tactic causes exposure."],
      },
      {
        id: "tiktok-for-you-delivery-hypothesis",
        text: "Making a video's topic and payoff clear early is a sensible creative hypothesis to test against actual viewing behavior, not an official ranking command.",
        kind: "hypothesis",
        sourceIds: ["tiktok-recommendations"],
        context: "A lab planning choice under limited source access.",
        limitations: ["The source does not validate this template or a particular opening length.", "Recommendation exposure changes the audience seeing each variant."],
      },
    ],
    practicalChoices: ["Use one legible opening that names the activity or question; compare it with a direct answer.", "Keep the promised demonstration in the video rather than delaying it until a separate post.", "Use captions and a coherent visual sequence; keep pace and duration fixed when testing the opening."],
    metric: {
      name: "Full-watch rate",
      numerator: "Eligible video starts that reached the end, at most once per counted start",
      denominator: "Eligible starts of the same video in the same reporting window",
      caveat: "Use one analytics definition for both variants. Replays, loops and platform-defined views may differ from starts; do not mix their counts. Completion is not satisfaction or proof of recommendation causality.",
    },
    qualityGuardrails: ["The ending resolves the opening promise.", "Check substantive feedback and confusion, not only completion.", "Avoid strobing, artificial distress and forced rewatch loops."],
    confounders: ["Personalized audience selection and distribution", "Topic interest, sound or trend changes", "Duration, pacing and replay behavior", "Posting time, moderation and competition"],
    sourceIds: ["tiktok-recommendations"],
  },
  {
    id: "tiktok-search",
    name: "TikTok Search",
    channel: "search",
    surface: "Search",
    kind: "ranked-surface",
    summary: "Start with an explicit query and the answer a searcher needs. Do not treat a For You hook as a documented Search-ranking factor.",
    rankingDisclosure: "Official index only: the help article body was access-restricted. Search is a separate surface; no verified full retrieval pipeline, exact Search weights or keyword-volume data are supplied here.",
    signals: [
      {
        id: "tiktok-search-scope",
        text: "TikTok's official recommendation help index includes Search as a distinct surface. That does not make its ranking interchangeable with For You.",
        kind: "official-disclosure",
        sourceIds: ["tiktok-recommendations"],
        context: "Official index-level surface information, with direct body access restricted.",
        limitations: ["Index only; detailed, current Search-specific weighting was not verified.", "This entry cannot tell you query volume, likely rank or a guaranteed discovery method."],
      },
      {
        id: "tiktok-search-intent-hypothesis",
        text: "Matching the visible question, on-screen explanation and demonstrated answer to one search intent is a planning hypothesis, not a known formula for ranking.",
        kind: "hypothesis",
        sourceIds: ["tiktok-recommendations"],
        context: "A search-oriented content brief proposed by this lab.",
        limitations: ["The limited reference does not prove a causal effect of a keyword in any specific field.", "Do not claim search demand or ranking gains without your own appropriately scoped observations."],
      },
    ],
    practicalChoices: ["Write the query as a real user question, then show the answer in the same video.", "Keep the spoken explanation, caption and on-screen topic accurate and consistent, without keyword stuffing.", "Record query, region, date and search context when manually observing results; do not assume another user's results match."],
    metric: {
      name: "Search-result selection rate (when measurable)",
      numerator: "Eligible Search-result presentations that led to viewing this result",
      denominator: "Eligible presentations of this result for the same query cohort and window",
      caveat: "Use only if a consistent search-specific exposure denominator is actually available, or measure it in a controlled search-task study. A share of views attributed to Search is not a click-through rate. Missing exposure data means this rate is unavailable.",
    },
    qualityGuardrails: ["A viewer can answer the original query after watching.", "Do not use an irrelevant trending term to acquire mismatched visits.", "Inspect query-specific confusion and whether the answer remains current."],
    confounders: ["Query mix, region, language and personalization", "Unknown result exposure and rank changes", "Search demand, competing results and trend shifts", "Differences in analytics attribution and observation window"],
    sourceIds: ["tiktok-recommendations"],
  },
  {
    id: "youtube-home",
    name: "YouTube Home",
    channel: "social",
    surface: "Home",
    kind: "ranked-surface",
    summary: "Recommendations respond to a viewer's history and satisfaction-related information. Make the title-thumbnail promise match the video rather than optimizing clicks alone.",
    rankingDisclosure: "Official high-level recommendation guidance, not a complete algorithm. Home relies primarily on watch history; disclosed signals vary by surface and no fixed weights are supplied.",
    signals: [
      {
        id: "youtube-home-personalization",
        text: "YouTube says Home recommendations rely primarily on watch history, within a broader recommendation system using signals such as viewing activity, subscriptions and feedback.",
        kind: "official-disclosure",
        sourceIds: ["youtube-recommendations"],
        context: "YouTube Home, not the Shorts feed or a search-ranking specification.",
        limitations: ["Different recommendation surfaces use signals differently.", "The document does not reveal a full candidate pipeline or exact signal weights."],
      },
      {
        id: "youtube-home-satisfaction",
        text: "YouTube's recommendation explanation includes satisfaction surveys and user feedback; watch time alone is not a full account of viewer value.",
        kind: "official-disclosure",
        sourceIds: ["youtube-recommendations"],
        context: "Official explanation of recommendation inputs, not a creator-visible score.",
        limitations: ["Creators cannot reconstruct internal satisfaction predictions from their click rate.", "A single video's analytics do not identify why the recommendation system changed exposure."],
      },
    ],
    practicalChoices: ["Make one specific title promise and use a thumbnail that accurately represents the video.", "Deliver evidence or a demonstration early, with a clear route through the rest of the video.", "When testing a title frame, hold the thumbnail and video fixed rather than silently testing a different package."],
    metric: {
      name: "Home impression click-through rate",
      numerator: "Views attributed to eligible Home thumbnail impressions",
      denominator: "Eligible Home thumbnail impressions in the same window",
      caveat: "Use Home-filtered data when available; broader Browse features are not necessarily Home alone. Total views, external views and all-surface impressions are not interchangeable. CTR can change when YouTube broadens the audience.",
    },
    qualityGuardrails: ["Review retention and whether the promised answer actually arrives.", "Inspect feedback about misleading titles, including disappointment despite a click.", "Do not sacrifice accuracy or accessibility to a more selectable thumbnail."],
    confounders: ["Viewer watch history and recommendation exposure", "Audience breadth, subscriber mix and returning viewers", "Topic demand, competing videos and seasonality", "Thumbnail, title or video changes made together"],
    sourceIds: ["youtube-recommendations"],
  },
  {
    id: "youtube-shorts",
    name: "YouTube Shorts",
    channel: "social",
    surface: "Shorts feed",
    kind: "ranked-surface",
    summary: "In a swipeable feed, choosing to watch, continued viewing and satisfaction are different questions. Test an opening without changing the lesson it leads to.",
    rankingDisclosure: "Official Shorts discovery guidance describes personalization and performance signals, including choosing to view, retention and satisfaction-related feedback. It does not publish a universal weighting formula.",
    signals: [
      {
        id: "youtube-shorts-choice-retention",
        text: "YouTube's Shorts guidance describes whether viewers choose to watch, average view duration and average percentage viewed as signals considered in discovery.",
        kind: "official-disclosure",
        sourceIds: ["youtube-shorts-discovery"],
        context: "Shorts recommendation and discovery guidance.",
        limitations: ["No universal duration, completion threshold or guaranteed distribution is disclosed here.", "These are distinct signals, not interchangeable denominators for one viral score."],
      },
      {
        id: "youtube-shorts-feedback-context",
        text: "The guidance also discusses likes, dislikes and post-watch survey information, while noting topic interest, competition and seasonality as influences on reach.",
        kind: "official-disclosure",
        sourceIds: ["youtube-shorts-discovery"],
        context: "Shorts satisfaction-related feedback and discovery context.",
        limitations: ["High performance on one measure does not guarantee impressions.", "Survey inputs and ranking predictions are not fully visible in creator analytics."],
      },
    ],
    practicalChoices: ["For a tutorial, compare a direct-answer opening with one concrete question; use the same demonstration after the opening.", "Keep framing, captions, duration, audio and CTA fixed so the opening is the treatment.", "Resolve the question before asking for any optional next action; do not hide the answer in a forced loop."],
    metric: {
      name: "Chose-to-view rate",
      numerator: "Eligible Shorts-feed presentations recorded as choosing to view rather than swiping away",
      denominator: "Eligible Shorts-feed presentations with a recorded view-or-swipe decision in the same window",
      caveat: "Use the same viewed-versus-swiped-away definition for both variants. Total views, replays and feed presentations are different units; do not divide all-platform views by feed exposures. Verify the analytics definition before entering counts.",
    },
    qualityGuardrails: ["Check retention or completion with a consistent definition and unchanged duration.", "Read feedback about whether the actual lesson satisfied the opening promise.", "Reject apparent gains caused by confusing loops, withheld answers or inaccessible presentation."],
    confounders: ["Topic interest, competition and seasonality", "Audience mix selected by recommendations", "Duration, repeat views and changing view definitions", "Posting time and unequal distribution"],
    sourceIds: ["youtube-shorts-discovery"],
  },
  {
    id: "google-search",
    name: "Google Search",
    channel: "search",
    surface: "Web Search",
    kind: "ranked-surface",
    summary: "Build the page that answers the query with original, reliable evidence. Content guidance and canonicalization are useful, but neither is a ranking guarantee.",
    rankingDisclosure: "Official people-first guidance is not a complete retrieval or ranking specification. Canonicalization concerns choosing representative URLs among duplicates; it is not an emotional-engagement signal.",
    signals: [
      {
        id: "google-search-people-first",
        text: "Google recommends helpful, reliable content made for people, including original information, clear sourcing and a satisfying experience for the intended reader.",
        kind: "official-disclosure",
        sourceIds: ["google-people-first"],
        context: "Search Central content-quality guidance, not a list of independent ranking weights.",
        limitations: ["The guidance does not establish a fixed ranking formula or guarantee indexation and rank.", "E-E-A-T is not a single ranking factor; a checklist score here would be invented.", "This registry provides no live query volume or competitor measurements."],
      },
      {
        id: "google-search-canonicalization",
        text: "Google may select a representative canonical URL among duplicate or very similar pages; the publisher's declared canonical is a signal rather than an instruction that must be followed.",
        kind: "official-disclosure",
        sourceIds: ["google-canonicalization"],
        context: "URL consolidation and indexing, separate from the creative appeal of a title.",
        limitations: ["A canonical declaration does not guarantee Google's chosen URL, indexing or ranking.", "Canonicalization is not a substitute for a useful page and original evidence."],
      },
    ],
    practicalChoices: ["Write the search intent and related questions before drafting a descriptive title and answer-first outline.", "Supply your own demonstration, experience or clearly sourced evidence; make authorship and limits visible.", "Keep each page's purpose clear and use consistent canonical signals for actual duplicates rather than producing thin near-copies."],
    metric: {
      name: "Search click-through rate",
      numerator: "Search clicks for the specified page and query cohort",
      denominator: "Search impressions for that same page, query cohort and window",
      caveat: "Use consistent Search Console filters for search type, country and device when available. Aggregate CTR is confounded by query mix, rank and search features; a before/after title comparison is not a randomized causal test.",
    },
    qualityGuardrails: ["A visitor can accomplish the stated intent without returning just to find a missing basic answer.", "Check factual accuracy, current evidence, clear limitations and useful downstream action.", "Avoid misleading titles, thin duplicates and content written mainly to manipulate ranking."],
    confounders: ["Rank, query mix, device, geography and search features", "Indexing, canonical selection and title rewrites", "Seasonality, demand and competitor changes", "Algorithm updates and delayed reporting"],
    sourceIds: ["google-people-first", "google-canonicalization"],
  },
  {
    id: "marketing-email",
    name: "Marketing email",
    channel: "email",
    surface: "Permission-based email campaign",
    kind: "strategy-channel",
    summary: "A strategy channel for a truthful promise, useful evidence and a clear next step. It has no single official ranking formula in this catalogue.",
    rankingDisclosure: "Strategy channel, not an official ranking system. Inbox providers have distinct delivery and filtering systems; no provider-specific delivery, inbox placement or ranking formula is claimed here.",
    signals: [
      {
        id: "email-promise-hypothesis",
        text: "A specific subject-line promise aligned with the body is a candidate for testing useful response. Headline research can inspire a question, but cannot predict an email lift.",
        kind: "hypothesis",
        sourceIds: ["curiosity-2025", "negative-headlines-2023"],
        context: "Editorial transfer hypothesis for an opted-in, nonpolitical email audience.",
        limitations: ["News-headline tests are not email experiments, and headline assignment does not isolate word attributes.", "List composition and delivery can change who has a chance to respond."],
      },
      {
        id: "email-evidence-hypothesis",
        text: "Verified experiences and genuine deadlines can clarify an offer when their source, scope and terms are supplied. Whether their presentation improves useful response is a local hypothesis.",
        kind: "hypothesis",
        sourceIds: ["social-influence-2006", "scarcity-1994"],
        context: "An optional offer-framing experiment, not a disclosed inbox-ranking signal.",
        limitations: ["The music-market and older scarcity studies do not establish email conversion effects.", "Never generate testimonials, availability counts or deadlines; missing evidence remains an unfilled requirement."],
      },
    ],
    practicalChoices: ["Write a specific promise, body evidence, all material terms and one clear CTA for the stated audience.", "If testing a subject line, hold sender, preview text, body, offer and destination fixed.", "Use consented recipients and an easy unsubscribe; do not optimize shame, fake scarcity or hidden costs."],
    metric: {
      name: "Unique-recipient click rate",
      numerator: "Delivered recipients who clicked the intended CTA at least once, excluding identified automated clicks",
      denominator: "Recipients with a delivered message in the same assigned variant and window",
      caveat: "Deduplicate by recipient and document bot filtering; security scanners can inflate clicks. Opens are not a reliable proxy for reading. Compare delivery rates too: conditioning only on delivered mail can break a randomized-group comparison if delivery differs.",
    },
    qualityGuardrails: ["Record unsubscribes, spam complaints and negative replies alongside useful follow-through.", "The destination fulfills the subject-line promise and displays the complete offer.", "Review delivery differences and whether clickers actually understood the terms."],
    confounders: ["Consent history, list source and audience mix", "Deliverability, automated clicks and privacy protections", "Send time, prior contact and concurrent campaigns", "Offer availability or destination changes"],
    sourceIds: ["curiosity-2025", "negative-headlines-2023", "social-influence-2006", "scarcity-1994"],
  },
  {
    id: "marketing-offer",
    name: "Marketing offer",
    channel: "offer",
    surface: "Offer or landing page",
    kind: "strategy-channel",
    summary: "Present value, evidence, price and constraints so someone can make an informed decision. This is a strategy channel, not an official ranking algorithm.",
    rankingDisclosure: "No single official rank formula. This entry proposes testable presentation choices on a page you control; it does not claim that urgency, reviews or conversion rate are search or social ranking factors.",
    signals: [
      {
        id: "offer-proof-hypothesis",
        text: "Showing one relevant, verified experience near the offer may help people assess fit, but the music-market social-influence experiment does not establish a landing-page conversion effect.",
        kind: "hypothesis",
        sourceIds: ["social-influence-2006"],
        context: "A proposed evidence-presentation comparison on a nonpolitical product or service page.",
        limitations: ["A testimonial must be real, attributable, permitted and relevant, not generated proof.", "A higher conversion rate does not establish that buyers made better-informed decisions."],
      },
      {
        id: "offer-real-constraint-hypothesis",
        text: "Explaining a genuine capacity limit can be compared with stating the same limit alone. This is a hypothesis about clarity, not a licence to manufacture scarcity.",
        kind: "hypothesis",
        sourceIds: ["scarcity-1994"],
        context: "A real limited-capacity offer with complete terms in both variants.",
        limitations: ["A small 1994 product-evaluation study cannot forecast sales or satisfaction for this offer.", "If no verified limit exists, omit the scarcity treatment rather than inventing one."],
      },
    ],
    practicalChoices: ["State the benefit, who it is and is not for, evidence, all-in price and cancellation or renewal terms before asking for a commitment.", "Use only operator-supplied proof and limits; leave explicit evidence requirements unfilled until verified.", "Randomly allocate eligible visitors if your own setup supports it; otherwise label variant observations as descriptive."],
    metric: {
      name: "Eligible-visitor conversion rate",
      numerator: "Eligible visitors completing the predefined action, counted once per assigned visitor",
      denominator: "Eligible visitors assigned and exposed to the same offer variant in the observation window",
      caveat: "Define the action and eligibility before launch; deduplicate repeat visits and keep assignment stable. Track cancellations and refunds after conversion. Page traffic before/after a change is not random assignment.",
    },
    qualityGuardrails: ["Track cancellations, refunds, complaints and misunderstood terms after the initial action.", "Keep the same truthful price, eligibility, proof and material terms in both variants.", "Make declining, comparing and leaving possible without shame or obstruction."],
    confounders: ["Traffic source, device and returning-visitor mix", "Concurrent ads, price changes and competing offers", "Remaining inventory, capacity and seasonality", "Unequal assignment, repeat visitors and checkout failures"],
    sourceIds: ["social-influence-2006", "scarcity-1994"],
  },
];

export const PLATFORM_BY_ID: Readonly<Record<PlatformId, Platform>> = Object.fromEntries(
  PLATFORMS.map((platform) => [platform.id, platform]),
) as Record<PlatformId, Platform>;

export function getPlatform(id: string): Platform | undefined {
  return Object.hasOwn(PLATFORM_BY_ID, id) ? PLATFORM_BY_ID[id as PlatformId] : undefined;
}
