import type { Source, SourceId } from "./schema";

export const SOURCES: readonly Source[] = [
  {
    id: "curiosity-2025",
    title: "When curiosity gaps backfire: effects of headline concreteness on information selection decisions",
    url: "https://doi.org/10.1038/s41598-024-81575-9",
    publisher: "Aubin Le Quéré & Matias · Scientific Reports",
    publishedAt: "2025",
    reviewedAt: "2026-09-08",
    context: "Research on headline concreteness and information selection using online headline tests. Random assignment concerns complete headline alternatives, not an independently manipulated word attribute.",
    retrievalLimitations: "Editorial review uses the approved research references; the publisher page was not re-retrieved on the review date. Do not treat a headline-feature association as an isolated causal effect or extrapolate it to every platform.",
  },
  {
    id: "arousal-replication-2024",
    title: "Does Physiological Arousal Increase Social Transmission of Information?",
    url: "https://doi.org/10.1177/09567976241257255",
    publisher: "Prowten et al. · Psychological Science",
    publishedAt: "2024",
    reviewedAt: "2026-09-08",
    context: "Two preregistered replication studies did not detect the proposed effect of exercise-induced incidental arousal on reported willingness to share news. The outcome was sharing willingness, not observed sharing on a social platform.",
    retrievalLimitations: "Editorial review uses the approved research references; no fresh full-text retrieval. Null findings constrain a general claim that arousal increases sharing; they are not a blanket disproof of every emotional effect, medium or population.",
  },
  {
    id: "moral-emotion-2017",
    title: "Emotion shapes the diffusion of moralized content in social networks",
    url: "https://doi.org/10.1073/pnas.1618923114",
    publisher: "Brady et al. · Proceedings of the National Academy of Sciences",
    publishedAt: "2017",
    reviewedAt: "2026-09-08",
    context: "Observational analysis of moral-emotional language and diffusion in political Twitter discussions. Network and topic context matter; the study is not an experiment assigning language to people.",
    retrievalLimitations: "Editorial review uses the approved research references; no fresh full-text retrieval. Associations do not establish a causal wording effect or transfer to nonpolitical content. Included for media literacy, not targeted political persuasion.",
  },
  {
    id: "negative-headlines-2023",
    title: "Negativity drives online news consumption",
    url: "https://doi.org/10.1038/s41562-023-01538-4",
    publisher: "Robertson et al. · Nature Human Behaviour",
    publishedAt: "2023",
    reviewedAt: "2026-09-08",
    context: "Headline-test data from Upworthy and analysis of negative language in relation to click-through. Readers were randomly assigned whole headline alternatives in that publisher's testing environment.",
    retrievalLimitations: "Editorial review uses the approved research references; no fresh full-text retrieval. Random assignment of headlines does not independently isolate negative words from other headline differences. Click-through is not trust, satisfaction, learning or sales.",
  },
  {
    id: "social-influence-2006",
    title: "Experimental Study of Inequality and Unpredictability in an Artificial Cultural Market",
    url: "https://doi.org/10.1126/science.1121066",
    publisher: "Salganik, Dodds & Watts · Science",
    publishedAt: "2006",
    reviewedAt: "2026-09-08",
    context: "An artificial music market compared independent choice with conditions exposing participants to other listeners' choices. Social influence changed the distribution and predictability of success.",
    retrievalLimitations: "Editorial review uses the approved research references; no fresh full-text retrieval. A controlled music-market result does not establish that a review badge improves conversion, that popularity measures quality, or that any individual item will benefit.",
  },
  {
    id: "scarcity-1994",
    title: "Scarcity and preference: An experiment on unavailability and product evaluation",
    url: "https://doi.org/10.1016/0167-4870(94)90007-8",
    publisher: "Verhallen & Robben · Journal of Economic Psychology",
    publishedAt: "1994",
    reviewedAt: "2026-09-08",
    context: "A small, older experiment on availability explanations and product evaluation. The reason an item is unavailable matters to interpreting scarcity.",
    retrievalLimitations: "Editorial review uses the approved research references; no fresh full-text retrieval. The study is not a modern ecommerce field trial, does not establish a universal sales lift and does not validate fake timers or invented stock counts.",
  },
  {
    id: "meta-feed-2022",
    title: "Instagram Feed ranking — historical system card",
    url: "https://ai.meta.com/tools/system-cards/instagram-feed-ranking/",
    publisher: "Meta",
    publishedAt: "2022",
    reviewedAt: "2026-09-08",
    context: "Historical 2022 disclosure of Instagram Feed candidate selection, predictions and ranking. The scope is Feed, not Reels, Explore or all of Instagram.",
    retrievalLimitations: "Historical reference, not a freshly verified 2026 specification. The URL may now present a changed document. No current signal weights, complete model, or outcome guarantee are established by this record.",
  },
  {
    id: "tiktok-recommendations",
    title: "How TikTok recommends content",
    url: "https://support.tiktok.com/en/using-tiktok/exploring-videos/how-tiktok-recommends-content",
    publisher: "TikTok Help Center",
    publishedAt: null,
    reviewedAt: "2026-09-08",
    context: "Official help-index information about recommendations, including For You and Search. These are separate surfaces, not one interchangeable algorithm.",
    retrievalLimitations: "Official index only: direct access to the article body was restricted during the approved research. Broad signal families are recorded conservatively; exact wording, current weights and a complete surface-specific pipeline were not verified. No new retrieval was performed on the editorial review date.",
  },
  {
    id: "youtube-shorts-discovery",
    title: "Search and discovery tips — Shorts",
    url: "https://support.google.com/youtube/answer/11914225?hl=en",
    publisher: "YouTube Help",
    publishedAt: null,
    reviewedAt: "2026-09-08",
    context: "Official explanation of Shorts discovery, viewer personalization, choosing to view, retention and satisfaction-related signals; topic interest, competition and seasonality also affect exposure.",
    retrievalLimitations: "Living help document; publication date and model weights are not supplied here. Reviewed against the approved research reference, not freshly fetched. The disclosure is directional guidance, not a deterministic reach formula.",
  },
  {
    id: "youtube-recommendations",
    title: "How YouTube recommendations work",
    url: "https://support.google.com/youtube/answer/16089387?hl=en",
    publisher: "YouTube Help",
    publishedAt: null,
    reviewedAt: "2026-09-08",
    context: "Official overview of recommendation signals and differences between surfaces. Home relies primarily on watch history; recommendations also use feedback and satisfaction information rather than watch time alone.",
    retrievalLimitations: "Living help document; publication date and exact weights are unknown here. Reviewed against the approved reference, not freshly fetched. Home guidance must not be substituted for Shorts or search ranking.",
  },
  {
    id: "google-people-first",
    title: "Creating helpful, reliable, people-first content",
    url: "https://developers.google.com/search/docs/fundamentals/creating-helpful-content",
    publisher: "Google Search Central",
    publishedAt: null,
    reviewedAt: "2026-09-08",
    context: "Guidance for assessing useful, reliable content made for people, including original information, clear sourcing and a satisfying answer. Not a checklist of directly measurable ranking weights.",
    retrievalLimitations: "Living documentation reviewed through the approved reference, not newly retrieved. The guidance does not reveal a complete retrieval or ranking algorithm, keyword volumes, or guaranteed positions. E-E-A-T is not a single ranking factor.",
  },
  {
    id: "google-canonicalization",
    title: "What is URL canonicalization",
    url: "https://developers.google.com/search/docs/crawling-indexing/canonicalization",
    publisher: "Google Search Central",
    publishedAt: null,
    reviewedAt: "2026-09-08",
    context: "How Google identifies a representative URL among duplicate or very similar pages. Canonicalization concerns indexing and consolidation, not emotional appeal.",
    retrievalLimitations: "Living documentation reviewed through the approved reference, not newly retrieved. A declared canonical is a signal, not a guarantee of Google's selected canonical or of indexing and ranking.",
  },
  {
    id: "google-trends-faq",
    title: "FAQ about Google Trends data",
    url: "https://support.google.com/trends/answer/4365533?hl=en",
    publisher: "Google Trends Help",
    publishedAt: null,
    reviewedAt: "2026-09-08",
    context: "Google Trends uses sampled search data and normalized relative interest. Values from 0 to 100 depend on the chosen comparison, geography, time range and search type; they are not absolute search volumes.",
    retrievalLimitations: "Living help document reviewed through the approved reference, not newly retrieved. Independently normalized exports are not automatically comparable, a zero may reflect insufficient data, and a spike does not identify its cause. This app does not fetch live Trends data.",
  },
];

export const SOURCE_BY_ID: Readonly<Record<SourceId, Source>> = Object.fromEntries(
  SOURCES.map((source) => [source.id, source]),
) as Record<SourceId, Source>;

export function getSource(id: string): Source | undefined {
  return Object.hasOwn(SOURCE_BY_ID, id) ? SOURCE_BY_ID[id as SourceId] : undefined;
}
