import Link from "next/link";
import { EvidenceLabel } from "@/components/attention/evidence-label";
import { pageMetadata } from "@/lib/site";

export const metadata = pageMetadata("Methodology", "How the Attention Lab distinguishes official disclosures, experiments, observations and hypotheses — and why a template or detector flag is not a scientific verdict.", "/methodology");

export default function MethodologyPage() {
  return (
    <main className="attention-page"><div className="attention-container">
      <header className="attention-page-header"><p className="attention-kicker">How this notebook thinks</p><h1 className="attention-title">Useful. Sourced.<br /><em>Open to correction.</em></h1><p className="attention-lead">Understanding attention should make your decisions more informed, not replace one persuasive certainty with another.</p></header>
      <div className="attention-reading-layout">
        <aside className="attention-reading-aside"><nav aria-label="Methodology contents"><p className="attention-kicker">On this page</p><a href="#evidence">Evidence labels</a><a href="#transfer">The transfer problem</a><a href="#experiments">What the Lab does</a><a href="#checker">What a checker flag means</a><a href="#trends">Reading trend context</a><a href="#boundaries">Our boundaries</a></nav></aside>
        <div className="attention-reading-body">
          <section className="attention-reading-section" id="evidence"><p className="attention-kicker">01 / Label the claim, not the whole idea</p><h2>Four kinds of evidence.</h2><p>Labels describe where a claim comes from. They are not a confidence score, a quality ranking or a guarantee that a finding transfers to your audience.</p>
            <article className="methodology-evidence" id="official-disclosure"><EvidenceLabel kind="official-disclosure" /><h3>What a platform says about its system.</h3><p>Official documentation can describe a surface, signal family or system stage. It is not an independent audit, a complete model or a current list of weights. Historical disclosures stay marked as historical; restricted access stays visible.</p></article>
            <article className="methodology-evidence" id="experimental"><EvidenceLabel kind="experimental" /><h3>What was varied in a study.</h3><p>Experiments can support comparisons within their design and context. In headline datasets, readers may be randomized to whole headlines without independently randomizing each word attribute. An analysis of negativity or concreteness is not automatically an isolated causal effect of that feature.</p><p>Null and replication findings matter. The arousal entry does not turn an unreliable sharing effect into a universal virality rule.</p></article>
            <article className="methodology-evidence" id="observational"><EvidenceLabel kind="observational" /><h3>What occurred together.</h3><p>Observed associations can motivate questions but do not establish that changing one feature causes an outcome. The moral-emotional diffusion research concerns historical political Twitter networks; network, author and topic differences can travel with the words.</p></article>
            <article className="methodology-evidence" id="hypothesis"><EvidenceLabel kind="hypothesis" /><h3>What is worth asking next.</h3><p>An editorial suggestion or creative template is a proposition to examine, not a published result. Sources can motivate it without validating it. This label is especially important when moving from news headlines or a music-market experiment to an email or an offer page.</p></article>
          </section>
          <section className="attention-reading-section" id="transfer"><p className="attention-kicker">02 / Keep context attached</p><h2>A study is not a strategy guarantee.</h2><ul className="attention-list"><li>Population, time, language, platform and task can all change what a finding means.</li><li>A click is not satisfaction, a share is not endorsement, and conversion is not informed choice.</li><li>Mechanism-to-platform compatibility marks a possible planning context, not a proven effect.</li><li>Publication dates retain their known precision. Unknown dates remain unknown. Editorial review dates are not fresh-retrieval dates.</li><li>The source register is a selected starting set, not a systematic review or an exhaustive account of the literature.</li></ul><Link className="attention-text-link" href="/sources">Inspect sources and access limits <span aria-hidden="true">↗</span></Link></section>
          <section className="attention-reading-section" id="experiments"><p className="attention-kicker">03 / Understand → Apply → Test</p><h2>A brief is a plan, not a prediction.</h2><p>The Lab uses deterministic, research-informed templates in your browser. It does not call a model, measure your audience, fetch platform data or publish content. Your topic, audience description, objective, surface, mechanism and supplied evidence shape an editable brief.</p><p>Define one changed variable, hold other features constant, choose a primary metric with an eligible denominator, and record quality or trust guardrails, an observation window, stopping rules and confounders before looking at outcomes.</p><h3>What the outcome calculator can say</h3><p>Manually entered nonnegative integer counts are checked so outcomes cannot exceed eligible observations. The calculator reports rates and their percentage-point difference. Relative lift requires a positive baseline; zero denominators remain unavailable.</p><p>Those calculations do not assign a winner, establish statistical significance or prove causation. Separate social posts and before/after SEO comparisons are descriptive unless an appropriate randomized design actually exists. Even randomization needs sound execution, stable definitions and a suitable analysis.</p><div className="attention-note"><strong>Success is not “the bigger number.”</strong> Check promise fulfillment, accuracy, comprehension, accessibility, complaints, cancellations and the freedom to decline. No improvement is a valid observation.</div><Link href="/lab" className="attention-text-link">Build a bounded experiment <span aria-hidden="true">↗</span></Link></section>
          <section className="attention-reading-section" id="checker"><p className="attention-kicker">04 / The decoder boundary</p><h2>A flag is a prompt to examine.</h2><p>The free checker is a separate, existing detection system. Its rule matches and optional configured model can identify language patterns worth inspecting, not establish the sender’s intent, diagnose a reader’s emotion or prove that an offer is false.</p><p>Its older category reference labels are not this new research registry. The Atlas does not silently redefine detector categories, thresholds or the ruleset version. Selected scarcity and social-proof categories link to related research using stable IDs only; the checker does not claim to detect all six Atlas mechanisms.</p><p>Scam and phishing warnings retain their own priority. They are not repackaged as strategies to try. Checker text is not carried into the Lab through URLs or saved drafts.</p><div className="attention-actions"><Link href="/check" className="attention-text-link">Open the free checker <span aria-hidden="true">↗</span></Link><Link href="/privacy" className="attention-text-link">Read the data boundary <span aria-hidden="true">↗</span></Link></div></section>
          <section className="attention-reading-section" id="trends"><p className="attention-kicker">05 / Demand needs context</p><h2>A trend note is an observation.</h2><p>The Trends notebook is manual. It does not fetch a live feed, crawl pages or infer keyword volume. Record the source, topic, geography, date range, search type, comparison context and what you actually observed.</p><p>Google Trends’ 0–100 values describe normalized, sampled relative interest, not absolute search volume. Independently normalized exports are not automatically comparable; a zero can reflect insufficient data. A spike does not identify its cause.</p><Link href="/trends" className="attention-text-link">Keep a contextualized note <span aria-hidden="true">↗</span></Link></section>
          <section className="attention-reading-section" id="boundaries"><p className="attention-kicker">06 / Useful without coercion</p><h2>Keep the promise honest.</h2><p>No invented testimonials, resetting timers, fake stock counts, guaranteed rankings or universal virality scores. Missing evidence stays visibly unfilled. A public claim still needs your verification before publication.</p><p>Moral-emotional research is included for media literacy, not targeted political persuasion or outrage engineering. The proposed application is a general, nonpolitical clarity exercise; no sensitive-identity inference belongs in the brief.</p><p>The free, no-login checker remains available. An optional <Link href="/audit">audit service</Link> is separate from these research tools.</p></section>
        </div>
      </div>
    </div></main>
  );
}
